### ISSUE TITLE
https://gcpdiag.dev/gcpdiag.sh not found

### ISSUE THREAD

**Issue by bkw** [GoogleCloudPlatform/gcpdiag#28]
The installation method mentioned in the docs does not work currently:

```shell
$ curl https://gcpdiag.dev/gcpdiag.sh
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message></Error>%
```

**Comment by schweikert** [comment]
Thanks Bernhard for reporting this! The build is running right now but the gcpdiag.sh script should appear on gcpdiag.dev/gcpdiag.sh soon.
