### ISSUE TITLE
create keyring fails with not implemented

### ISSUE THREAD

**Issue by jetersen** [GoogleCloudPlatform/gcpdiag#43]
```
$ gcpdiag lint --project=test-1234
Error: OCI runtime error: create keyring `longid`: Function not implemented
```

**Comment by schweikert** [comment]
Are you running this on Cloud Shell or on your host? Seems to be related to Docker.

**Comment by jetersen** [comment]
Sorry forgot to include those details.

Ran on ChromeOS using podman.
The Linux OS has gnome keyring installed.

**Comment by schweikert** [comment]
Maybe https://ntk.me/2021/05/14/podman-in-crostini/ helps? Note that we want to use GitHub issues with bugs related to gcpdiag. This seems related to your installation. I will close it for now.

**Comment by jetersen** [comment]
Did not but close.

This helped https://github.com/containers/podman/issues/11037#issuecomment-947050246

Sorry for creating an issue but sometimes cross linking helps 👍

**Comment by schweikert** [comment]
Yes it does help, thank you!
