### ISSUE TITLE
gcs/BP/2022_001: Propose "Buckets are **not** using uniform access"

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/gcpdiag#59]
Very interesting project, thank you!

This rule would be better phrased as `Buckets not using uniform access`

The rules check for the incorrect behavior.

In this case, linting produced the following output which appears inconsistent (If the `Buckets are using uniform access` why the `[FAIL]`'s?). The reason is that the `Buckets are **not** using uniform access` (and should be)

```console
🔎  gcs/BP/2022_001: Buckets are using uniform access
   - {bucket}                                                                         [FAIL]
     it is recommend to use uniform access on your bucket
   - {bucket}                                                                         [FAIL]
     it is recommend to use uniform access on your bucket
```

**Comment by schweikert** [comment]
This is a bit confusing but the output is correct: the lint rules always describe a wanted state and fail if that wanted state is not true, so in this case they verify that the buckets are using uniform access, but that check fails.
