### ISSUE TITLE
gcs/BP/2022_001: Lint rule contradicts Google's default (!?) behavior w/ Cloud Build

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/gcpdiag#61]
```console
   - {project}_cloudbuild                                              [FAIL]
     it is recommend to use uniform access on your bucket
```

This bucket was auto-created by the Cloud Build service.

**Comment by ropeck** [comment]
Looks like a possible fix is to expand the list of labels that are skipped for this check. https://github.com/GoogleCloudPlatform/gcpdiag/blob/01878e5f35b9af528ae930a7558d92c555de1d6b/gcpdiag/lint/gcs/bp_2022_001_bucket_access_uniform.py#L27
The list includes composer now. We can skip dataproc and cloud build as well if they label the buckets with a naming pattern we can match in the rule.

**Comment by ropeck** [comment]
dataproc GCS buckets have the label 'goog-dataproc-location' which has the region. Any bucket with that label can be skipped as a dataproc cluster.

cloud build buckets do not have any unique labels, however the bucket name matches *_cloudbuild and artifacts.PROJECT_NAME.appspot.com, which could be skipped as they are generated by cloud build

**Comment by kaushik853** [comment]
Do you create a PR Rodney for this ?

**Comment by ropeck** [comment]
> Do you create a PR Rodney for this ? unfortunately i think we can not put wildcard mask * in ignore labels

I've made this change to add the dataproc label, and to check the bucket name for known patterns like the ones used for Cloud Build
https://github.com/GoogleCloudPlatform/gcpdiag/commit/a725db8dd0f86b0c1194637756d8a091bda5c069
